import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Kajol-Kibria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gradient-to-b from-blue-50 to-red-100 ">
        
          <Navbar/>
        
        <div >
          {children}
        </div>
        </div>
        </body>
    </html>
  );
}
